version: '3.1'

services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
